version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_trad
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3307:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_traducteur
    ports:
      - "3000:3000"  
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data:


